import { MatchOutcome, MatchStatsState, PlayerStats, TeamStats } from '../../../background/types/matchStatsTypes';
import { CharacterName } from 'lib/characterIcons';

const toTimestamp = (iso: string): number => new Date(iso).getTime();

const createPlayer = (overrides: Partial<PlayerStats>): PlayerStats => ({
  uid: 'placeholder',
  name: 'Player',
  characterName: CharacterName.IRON_MAN,
  characterId: 'placeholder',
  team: 1,
  isTeammate: true,
  isLocal: false,
  isAlive: true,
  kills: 0,
  finalHits: 0,
  deaths: 0,
  assists: 0,
  ultCharge: null,
  damageDealt: 0,
  damageBlocked: 0,
  totalHeal: 0,
  pctTeamDamage: 0,
  pctTeamBlocked: 0,
  pctTeamHealing: 0,
  lastUpdated: Date.now(),
  killedPlayers: {},
  killedBy: {},
  characterSwaps: [],
  ...overrides,
});

const createTeamStats = (overrides: Partial<TeamStats>): TeamStats => ({
  finalHits: 0,
  totalDamage: 0,
  totalBlocked: 0,
  totalHealing: 0,
  ...overrides,
});

export const matchHistoryTestData: MatchStatsState[] = [
  {
    matchId: 'TEST-MATCH-001',
    map: 'Avengers Tower',
    gameType: 'Ranked',
    gameMode: 'Payload',
    outcome: MatchOutcome.Victory,
    players: {
      'local-player': createPlayer({
        uid: 'local-player',
        name: 'Arc Reactor',
        characterName: CharacterName.IRON_MAN,
        characterId: 'iron_man',
        team: 1,
        isTeammate: true,
        isLocal: true,
        kills: 18,
        assists: 9,
        deaths: 4,
        finalHits: 6,
        ultCharge: 100,
        damageDealt: 18500,
        damageBlocked: 4100,
        totalHeal: 950,
        pctTeamDamage: 42,
        pctTeamBlocked: 35,
        pctTeamHealing: 12,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
        killedPlayers: {
          'enemy-1': 5,
          'enemy-2': 3,
        },
        killedBy: {
          'enemy-3': 2,
        },
      }),
      'ally-1': createPlayer({
        uid: 'ally-1',
        name: 'Shield Maiden',
        characterName: CharacterName.CAPTAIN_AMERICA,
        characterId: 'captain_america',
        team: 1,
        isTeammate: true,
        kills: 6,
        assists: 14,
        deaths: 3,
        finalHits: 2,
        damageDealt: 9600,
        damageBlocked: 8700,
        totalHeal: 0,
        pctTeamDamage: 22,
        pctTeamBlocked: 48,
        pctTeamHealing: 0,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
      }),
      'ally-2': createPlayer({
        uid: 'ally-2',
        name: 'Storm Front',
        characterName: CharacterName.STORM,
        characterId: 'storm',
        team: 1,
        isTeammate: true,
        kills: 8,
        assists: 11,
        deaths: 5,
        finalHits: 3,
        damageDealt: 12200,
        damageBlocked: 1200,
        totalHeal: 2500,
        pctTeamDamage: 27,
        pctTeamBlocked: 7,
        pctTeamHealing: 68,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
      }),
      'ally-3': createPlayer({
        uid: 'ally-3',
        name: 'Night Sentinel',
        characterName: CharacterName.WOLVERINE,
        characterId: 'wolverine',
        team: 1,
        isTeammate: true,
        kills: 7,
        assists: 6,
        deaths: 6,
        finalHits: 5,
        damageDealt: 10300,
        damageBlocked: 2600,
        totalHeal: 300,
        pctTeamDamage: 23,
        pctTeamBlocked: 10,
        pctTeamHealing: 8,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
        killedPlayers: { 'enemy-1': 1, 'enemy-3': 1 },
        killedBy: { 'enemy-2': 1 },
      }),
      'ally-4': createPlayer({
        uid: 'ally-4',
        name: 'Blade Runner',
        characterName: CharacterName.BLADE,
        characterId: 'daredevil',
        team: 1,
        isTeammate: true,
        kills: 3,
        assists: 5,
        deaths: 7,
        finalHits: 2,
        damageDealt: 5200,
        damageBlocked: 400,
        totalHeal: 100,
        pctTeamDamage: 8,
        pctTeamBlocked: 2,
        pctTeamHealing: 2,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
        killedPlayers: { 'enemy-4': 1 },
        killedBy: { 'enemy-1': 1 },
      }),
      'ally-5': createPlayer({
        uid: 'ally-5',
        name: 'Sable',
        characterName: CharacterName.BLACK_PANTHER,
        characterId: 'black_panther',
        team: 1,
        isTeammate: true,
        kills: 2,
        assists: 3,
        deaths: 5,
        finalHits: 1,
        damageDealt: 3200,
        damageBlocked: 200,
        totalHeal: 50,
        pctTeamDamage: 4,
        pctTeamBlocked: 1,
        pctTeamHealing: 1,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
        killedPlayers: { 'enemy-2': 1 },
      }),
      'enemy-1': createPlayer({
        uid: 'enemy-1',
        name: 'Arc Nemesis',
        characterName: CharacterName.MAGNETO,
        characterId: 'magneto',
        team: 2,
        isTeammate: false,
        isLocal: false,
        kills: 12,
        assists: 4,
        deaths: 9,
        finalHits: 5,
        damageDealt: 16900,
        damageBlocked: 2900,
        totalHeal: 400,
        pctTeamDamage: 44,
        pctTeamBlocked: 28,
        pctTeamHealing: 13,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
      }),
      'enemy-2': createPlayer({
        uid: 'enemy-2',
        name: 'Widow Byte',
        characterName: CharacterName.BLACK_WIDOW,
        characterId: 'black_widow',
        team: 2,
        isTeammate: false,
        isAlive: false,
        kills: 10,
        assists: 5,
        deaths: 11,
        finalHits: 2,
        damageDealt: 13100,
        damageBlocked: 700,
        totalHeal: 600,
        pctTeamDamage: 34,
        pctTeamBlocked: 7,
        pctTeamHealing: 20,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
      }),
      'enemy-3': createPlayer({
        uid: 'enemy-3',
        name: 'Lunar Echo',
        characterName: CharacterName.LUNA_SNOW,
        characterId: 'luna_snow',
        team: 2,
        isTeammate: false,
        kills: 5,
        assists: 12,
        deaths: 8,
        finalHits: 3,
        damageDealt: 9200,
        damageBlocked: 1100,
        totalHeal: 5400,
        pctTeamDamage: 24,
        pctTeamBlocked: 11,
        pctTeamHealing: 67,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
        killedPlayers: { 'ally-1': 1, 'ally-3': 1 },
      }),
      'enemy-4': createPlayer({
        uid: 'enemy-4',
        name: 'Silent Dagger',
        characterName: CharacterName.CLOAK_AND_DAGGER,
        characterId: 'cloak_and_dagger',
        team: 2,
        isTeammate: false,
        kills: 4,
        assists: 8,
        deaths: 10,
        finalHits: 3,
        damageDealt: 8800,
        damageBlocked: 500,
        totalHeal: 300,
        pctTeamDamage: 23,
        pctTeamBlocked: 3,
        pctTeamHealing: 0,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
      }),
      'enemy-5': createPlayer({
        uid: 'enemy-5',
        name: 'Iron Wraith',
        characterName: CharacterName.IRON_MAN,
        characterId: 'iron_man',
        team: 2,
        isTeammate: false,
        kills: 4,
        assists: 3,
        deaths: 9,
        finalHits: 2,
        damageDealt: 4600,
        damageBlocked: 200,
        totalHeal: 0,
        pctTeamDamage: 8,
        pctTeamBlocked: 2,
        pctTeamHealing: 0,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
        killedPlayers: { 'ally-4': 1 },
      }),
      'enemy-6': createPlayer({
        uid: 'enemy-6',
        name: 'Spectre',
        characterName: CharacterName.ULTRON,
        characterId: 'spectre',
        team: 2,
        isTeammate: false,
        kills: 2,
        assists: 1,
        deaths: 12,
        finalHits: 1,
        damageDealt: 2100,
        damageBlocked: 100,
        totalHeal: 0,
        pctTeamDamage: 4,
        pctTeamBlocked: 1,
        pctTeamHealing: 0,
        lastUpdated: toTimestamp('2024-06-01T19:45:30Z'),
        killedPlayers: {},
      }),
    },
    teamStats: {
      1: createTeamStats({
        finalHits: 20,
        totalDamage: 50600,
        totalBlocked: 16600,
        totalHealing: 3750,
      }),
      2: createTeamStats({
        finalHits: 15,
        totalDamage: 48000,
        totalBlocked: 5200,
        totalHealing: 6400,
      }),
    },
    timestamps: {
      matchStart: toTimestamp('2024-06-01T19:15:00Z'),
      matchEnd: toTimestamp('2024-06-01T19:34:45Z'),
    },
    rounds: [],
  },
  {
    matchId: 'TEST-MATCH-002',
    map: 'Wakanda Outpost',
    gameType: 'Unranked',
    gameMode: 'Domination',
    outcome: MatchOutcome.Defeat,
    players: {
      'local-player': createPlayer({
        uid: 'local-player',
        name: 'Arc Reactor',
        characterName: CharacterName.IRON_MAN,
        characterId: 'iron_man',
        team: 1,
        isTeammate: true,
        isLocal: true,
        kills: 9,
        assists: 12,
        deaths: 7,
        finalHits: 4,
        damageDealt: 13200,
        damageBlocked: 3300,
        totalHeal: 600,
        pctTeamDamage: 39,
        pctTeamBlocked: 31,
        pctTeamHealing: 15,
        lastUpdated: toTimestamp('2024-06-02T03:12:40Z'),
        killedPlayers: {
          'enemy-5': 2,
          'enemy-6': 1,
        },
        killedBy: {
          'enemy-7': 3,
        },
      }),
      'ally-4': createPlayer({
        uid: 'ally-4',
        name: 'Quantum Archer',
        characterName: CharacterName.HAWKEYE,
        characterId: 'hawkeye',
        team: 1,
        isTeammate: true,
        kills: 5,
        assists: 10,
        deaths: 9,
        finalHits: 1,
        damageDealt: 7600,
        damageBlocked: 500,
        totalHeal: 300,
        pctTeamDamage: 22,
        pctTeamBlocked: 5,
        pctTeamHealing: 8,
        lastUpdated: toTimestamp('2024-06-02T03:12:40Z'),
      }),
      'ally-5': createPlayer({
        uid: 'ally-5',
        name: 'Verdant Guardian',
        characterName: CharacterName.GROOT,
        characterId: 'groot',
        team: 1,
        isTeammate: true,
        kills: 2,
        assists: 14,
        deaths: 8,
        finalHits: 1,
        damageDealt: 5400,
        damageBlocked: 9100,
        totalHeal: 4800,
        pctTeamDamage: 16,
        pctTeamBlocked: 52,
        pctTeamHealing: 62,
        lastUpdated: toTimestamp('2024-06-02T03:12:40Z'),
      }),
      'ally-6': createPlayer({
        uid: 'ally-6',
        name: 'Radiant Frost',
        characterName: CharacterName.EMMA_FROST,
        characterId: 'emma_frost',
        team: 1,
        isTeammate: true,
        kills: 3,
        assists: 9,
        deaths: 11,
        finalHits: 0,
        damageDealt: 4400,
        damageBlocked: 700,
        totalHeal: 1100,
        pctTeamDamage: 13,
        pctTeamBlocked: 12,
        pctTeamHealing: 15,
        lastUpdated: toTimestamp('2024-06-02T03:12:40Z'),
      }),
      'enemy-5': createPlayer({
        uid: 'enemy-5',
        name: 'Helbound',
        characterName: CharacterName.HELA,
        characterId: 'hela',
        team: 2,
        isTeammate: false,
        kills: 15,
        assists: 6,
        deaths: 5,
        finalHits: 7,
        damageDealt: 18800,
        damageBlocked: 2600,
        totalHeal: 900,
        pctTeamDamage: 47,
        pctTeamBlocked: 28,
        pctTeamHealing: 18,
        lastUpdated: toTimestamp('2024-06-02T03:12:40Z'),
      }),
      'enemy-6': createPlayer({
        uid: 'enemy-6',
        name: 'Thunder Strike',
        characterName: CharacterName.THOR,
        characterId: 'thor',
        team: 2,
        isTeammate: false,
        kills: 11,
        assists: 8,
        deaths: 6,
        finalHits: 5,
        damageDealt: 15200,
        damageBlocked: 8200,
        totalHeal: 600,
        pctTeamDamage: 38,
        pctTeamBlocked: 52,
        pctTeamHealing: 12,
        lastUpdated: toTimestamp('2024-06-02T03:12:40Z'),
      }),
      'enemy-7': createPlayer({
        uid: 'enemy-7',
        name: 'Shadow Widow',
        characterName: CharacterName.BLACK_WIDOW,
        characterId: 'black_widow',
        team: 2,
        isTeammate: false,
        kills: 8,
        assists: 9,
        deaths: 7,
        finalHits: 2,
        damageDealt: 11100,
        damageBlocked: 900,
        totalHeal: 700,
        pctTeamDamage: 30,
        pctTeamBlocked: 6,
        pctTeamHealing: 20,
        lastUpdated: toTimestamp('2024-06-02T03:12:40Z'),
      }),
      'enemy-8': createPlayer({
        uid: 'enemy-8',
        name: 'Voidbreaker',
        characterName: CharacterName.DOCTOR_STRANGE,
        characterId: 'doctor_strange',
        team: 2,
        isTeammate: false,
        kills: 6,
        assists: 15,
        deaths: 9,
        finalHits: 1,
        damageDealt: 9800,
        damageBlocked: 1200,
        totalHeal: 5100,
        pctTeamDamage: 25,
        pctTeamBlocked: 14,
        pctTeamHealing: 50,
        lastUpdated: toTimestamp('2024-06-02T03:12:40Z'),
      }),
    },
    teamStats: {
      1: createTeamStats({
        finalHits: 6,
        totalDamage: 30600,
        totalBlocked: 13600,
        totalHealing: 6800,
      }),
      2: createTeamStats({
        finalHits: 15,
        totalDamage: 54900,
        totalBlocked: 12900,
        totalHealing: 7300,
      }),
    },
    timestamps: {
      matchStart: toTimestamp('2024-06-02T02:45:00Z'),
      matchEnd: toTimestamp('2024-06-02T03:21:10Z'),
    },
    rounds: [],
  },
  {
    matchId: 'TEST-MATCH-003',
    map: 'Helicarrier',
    gameType: 'Unranked',
    gameMode: 'Skirmish',
    outcome: MatchOutcome.Victory,
    players: {
      'p3-1': createPlayer({ uid: 'p3-1', name: 'Seraph', characterName: CharacterName.ANGELA, characterId: 'angela', team: 1, isTeammate: true, kills: 10, assists: 4, deaths: 3, finalHits: 2 }),
      'p3-2': createPlayer({ uid: 'p3-2', name: 'Starforged', characterName: CharacterName.ADAM_WARLOCK, characterId: 'adam_warlock', team: 1, isTeammate: true, kills: 6, assists: 8, deaths: 5, finalHits: 1 }),
      'p3-3': createPlayer({ uid: 'p3-3', name: 'Gamma Core', characterName: CharacterName.BRUCE_BANNER, characterId: 'bruce_banner', team: 1, isTeammate: true, kills: 3, assists: 2, deaths: 9, finalHits: 0 }),
      'p3-4': createPlayer({ uid: 'p3-4', name: 'Crusher', characterName: CharacterName.HULK, characterId: 'hulk', team: 1, isTeammate: true, kills: 12, assists: 2, deaths: 6, finalHits: 4 }),
      'p3-5': createPlayer({ uid: 'p3-5', name: 'Flare', characterName: CharacterName.HUMAN_TORCH, characterId: 'human_torch', team: 1, isTeammate: true, kills: 4, assists: 5, deaths: 7, finalHits: 1 }),
      'p3-6': createPlayer({ uid: 'p3-6', name: 'Invisible Ace', characterName: CharacterName.INVISIBLE_WOMAN, characterId: 'invisible_woman', team: 1, isTeammate: true, kills: 2, assists: 9, deaths: 4, finalHits: 0 }),

      'p3-7': createPlayer({ uid: 'p3-7', name: 'Iron Fist', characterName: CharacterName.IRON_FIST, characterId: 'iron_fist', team: 2, isTeammate: false, kills: 7, assists: 3, deaths: 8, finalHits: 2 }),
      'p3-8': createPlayer({ uid: 'p3-8', name: 'Land Shark', characterName: CharacterName.JEFF_THE_LAND_SHARK, characterId: 'jeff_the_land_shark', team: 2, isTeammate: false, kills: 5, assists: 4, deaths: 6, finalHits: 1 }),
      'p3-9': createPlayer({ uid: 'p3-9', name: 'Trickster', characterName: CharacterName.LOKI, characterId: 'loki', team: 2, isTeammate: false, kills: 9, assists: 6, deaths: 5, finalHits: 3 }),
      'p3-10': createPlayer({ uid: 'p3-10', name: 'Sage', characterName: CharacterName.MAGIK, characterId: 'magik', team: 2, isTeammate: false, kills: 4, assists: 7, deaths: 8, finalHits: 1 }),
      'p3-11': createPlayer({ uid: 'p3-11', name: 'Cosmic Mantis', characterName: CharacterName.MANTIS, characterId: 'mantis', team: 2, isTeammate: false, kills: 1, assists: 12, deaths: 3, finalHits: 0 }),
      'p3-12': createPlayer({ uid: 'p3-12', name: 'Reed', characterName: CharacterName.MISTER_FANTASTIC, characterId: 'mister_fantastic', team: 2, isTeammate: false, kills: 3, assists: 5, deaths: 9, finalHits: 0 }),
    },
    teamStats: {
      1: createTeamStats({ finalHits: 6, totalDamage: 24000, totalBlocked: 8000, totalHealing: 1000 }),
      2: createTeamStats({ finalHits: 9, totalDamage: 30000, totalBlocked: 4000, totalHealing: 500 }),
    },
    timestamps: {
      matchStart: toTimestamp('2024-06-03T12:00:00Z'),
      matchEnd: toTimestamp('2024-06-03T12:18:42Z'),
    },
    rounds: [],
  },
  {
    matchId: 'TEST-MATCH-004',
    map: 'Knowhere',
    gameType: 'Ranked',
    gameMode: 'Control',
    outcome: MatchOutcome.Defeat,
    players: {
      'p4-1': createPlayer({ uid: 'p4-1', name: 'Moon Shadow', characterName: CharacterName.MOON_KNIGHT, characterId: 'moon_knight', team: 1, isTeammate: true, kills: 8, assists: 2, deaths: 6, finalHits: 3 }),
      'p4-2': createPlayer({ uid: 'p4-2', name: 'Sea King', characterName: CharacterName.NAMOR, characterId: 'namor', team: 1, isTeammate: true, kills: 5, assists: 3, deaths: 7, finalHits: 2 }),
      'p4-3': createPlayer({ uid: 'p4-3', name: 'Tech Kid', characterName: CharacterName.PENI_PARKER, characterId: 'peni_parker', team: 1, isTeammate: true, kills: 2, assists: 11, deaths: 4, finalHits: 0 }),
      'p4-4': createPlayer({ uid: 'p4-4', name: 'Psi-Muse', characterName: CharacterName.PSYLOCKE, characterId: 'psylocke', team: 1, isTeammate: true, kills: 6, assists: 4, deaths: 6, finalHits: 1 }),
      'p4-5': createPlayer({ uid: 'p4-5', name: 'Rocket', characterName: CharacterName.ROCKET_RACCOON, characterId: 'rocket_raccoon', team: 1, isTeammate: true, kills: 7, assists: 3, deaths: 8, finalHits: 2 }),
      'p4-6': createPlayer({ uid: 'p4-6', name: 'Scarlet Hex', characterName: CharacterName.SCARLET_WITCH, characterId: 'scarlet_witch', team: 1, isTeammate: true, kills: 4, assists: 10, deaths: 5, finalHits: 1 }),

      'p4-7': createPlayer({ uid: 'p4-7', name: 'Friendly Spider', characterName: CharacterName.SPIDER_MAN, characterId: 'spider_man', team: 2, isTeammate: false, kills: 11, assists: 6, deaths: 4, finalHits: 4 }),
      'p4-8': createPlayer({ uid: 'p4-8', name: 'Squirrel Champ', characterName: CharacterName.SQUIRREL_GIRL, characterId: 'squirrel_girl', team: 2, isTeammate: false, kills: 3, assists: 9, deaths: 7, finalHits: 0 }),
      'p4-9': createPlayer({ uid: 'p4-9', name: 'Star Pilot', characterName: CharacterName.STAR_LORD, characterId: 'star_lord', team: 2, isTeammate: false, kills: 5, assists: 8, deaths: 6, finalHits: 2 }),
      'p4-10': createPlayer({ uid: 'p4-10', name: 'Punisher', characterName: CharacterName.THE_PUNISHER, characterId: 'the_punisher', team: 2, isTeammate: false, kills: 9, assists: 1, deaths: 9, finalHits: 3 }),
      'p4-11': createPlayer({ uid: 'p4-11', name: 'Thingy', characterName: CharacterName.THE_THING, characterId: 'the_thing', team: 2, isTeammate: false, kills: 2, assists: 2, deaths: 12, finalHits: 0 }),
      'p4-12': createPlayer({ uid: 'p4-12', name: 'Symbiote', characterName: CharacterName.VENOM, characterId: 'venom', team: 2, isTeammate: false, kills: 6, assists: 5, deaths: 7, finalHits: 2 }),
    },
    teamStats: {
      1: createTeamStats({ finalHits: 7, totalDamage: 21400, totalBlocked: 5300, totalHealing: 4200 }),
      2: createTeamStats({ finalHits: 11, totalDamage: 33200, totalBlocked: 9000, totalHealing: 900 }),
    },
    timestamps: {
      matchStart: toTimestamp('2024-06-04T08:22:00Z'),
      matchEnd: toTimestamp('2024-06-04T08:41:30Z'),
    },
    rounds: [],
  },
  {
    matchId: 'TEST-MATCH-005',
    map: 'Sokovia',
    gameType: 'Practice',
    gameMode: 'Payload',
    outcome: MatchOutcome.Victory,
    players: {
      'p5-1': createPlayer({ uid: 'p5-1', name: 'Winters', characterName: CharacterName.WINTER_SOLDIER, characterId: 'winter_soldier', team: 1, isTeammate: true, kills: 6, assists: 4, deaths: 5, finalHits: 1 }),
      'p5-2': createPlayer({ uid: 'p5-2', name: 'Phoenix Flame', characterName: CharacterName.PHOENIX, characterId: 'phoenix', team: 1, isTeammate: true, kills: 15, assists: 3, deaths: 2, finalHits: 6 }),
      'p5-3': createPlayer({ uid: 'p5-3', name: 'Ditto', characterName: CharacterName.DUELIST, characterId: 'duelist', team: 1, isTeammate: true, kills: 4, assists: 2, deaths: 8, finalHits: 0 }),

      // add a few duplicates so this match looks realistic and helps crosscover characters
      'p5-4': createPlayer({ uid: 'p5-4', name: 'Wasp', characterName: CharacterName.STORM, characterId: 'storm', team: 2, isTeammate: false, kills: 3, assists: 5, deaths: 6, finalHits: 1 }),
      'p5-5': createPlayer({ uid: 'p5-5', name: 'Rocket 2', characterName: CharacterName.ROCKET_RACCOON, characterId: 'rocket_raccoon', team: 2, isTeammate: false, kills: 7, assists: 4, deaths: 5, finalHits: 2 }),
      'p5-6': createPlayer({ uid: 'p5-6', name: 'Spider Girl', characterName: CharacterName.SPIDER_MAN, characterId: 'spider_man', team: 2, isTeammate: false, kills: 8, assists: 9, deaths: 3, finalHits: 3 }),
    },
    teamStats: {
      1: createTeamStats({ finalHits: 9, totalDamage: 28500, totalBlocked: 6100, totalHealing: 1600 }),
      2: createTeamStats({ finalHits: 6, totalDamage: 19300, totalBlocked: 4100, totalHealing: 800 }),
    },
    timestamps: {
      matchStart: toTimestamp('2024-06-05T14:05:00Z'),
      matchEnd: toTimestamp('2024-06-05T14:28:15Z'),
    },
    rounds: [],
  },
];
